service: layers-nodejs-modules
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: "hello"
          method: "get"
    layers: # o nome do recurso é criado pelo fw serverless ao montar o pacote do cloud formation / o nome referencia o ARN do layer
      - { Ref: NodeModulesLambdaLayer }
layers:
  NodeModules:
    path: layer
    compatibleRuntimes:
      - nodejs12.x
